sudo: required

language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - PYTHONPATH=lib

services:
  - docker

install:
  - pip install -r requirements.txt

script:
  - docker build .
  - behave features --tags ~@skip
  - ./lint

